-- Originally generated by nwg-displays on 2025-12-31.
-- If you regenerate with nwg-displays, check whether it now writes Lua
-- directly (0.55+ tooling may have caught up); if not, keep hand-editing this.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = 1.0,
})

-- From your general.conf (folded in here so all monitor config lives in one place):
hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

hl.monitor({
    output = "HDMI-A-1",
    mode = "preferred",
    position = "auto",
    scale = 1,
    mirror = "eDP-1",
})
